### ISSUE TITLE
Guidance how to start Shiny app

### ISSUE THREAD

**Issue by Studentenfutter** [jansim/WG-SuchR#1]
Hallo Jan!

Ich bin zufällig auf deine tolle Arbeit in diesem Projekt aufmerksam geworden, großes Kompliment! Leider habe ich nur geringe Erfahrung mit Shiny und bekomme die App leider nicht ans laufen, nach klonen des Repos und ausführen der server.R in inst/app erhalte ich folgenden Fehler:

```
runApp('inst/app')

Listening on http://127.0.0.1:4604
Warnung: Error in : $ operator is invalid for atomic vectors
  67: tag
  66: tags$a
  63: FUN
  62: lapply
  61: buildTabset
  60: shiny::tabsetPanel
  59: tabBox
```

Ich habe vorher ein wenig mit Dateien herumgespielt und der Webscraping-Teil mit rvest scheint noch einwandfrei zu funktionieren, zumindest erhalte ich einen Dataframe für Konstanz und kann diesen processen - lediglich die Funktion `data.by.stadtteil()` scheint nichts zu tun.

Es wäre aber super, wenn ich mir das ganze wie von dir vorgesehen im Shinyinterface ansehen könnte! Kannst du mir helfen / mich in die richtige Richtung stoßen?

Hier noch der output meiner `sessionInfo()`:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.3          shinydashboard_0.7.1 ggplot2_3.2.0        shiny_1.3.2         
[5] rvest_0.3.4          xml2_1.2.1           jsonlite_1.6 
```

**Comment by jansim** [comment]
Hi Studentenfutter!

Schön zu sehen, dass sich jemand für unser Projekt interessiert 😄 Ich habe noch einmal in den Code geschaut und konnte den Fehler replizieren. Nachdem ich ein paar Zeilen entfernt habe (die nie hätten da sein sollen 🤔 ) läuft es bei mir jetzt wieder.

Ich habe auch mal direkt eine Anleitung zum starten der shiny App in die Readme hinzugefügt, aber da hast du glaube ich schon alles richtig gemacht.

Du kannst ja mal sagen, ob der Fehler damit bei dir gelöst ist, dann würde ich den issue closen.

LG,
Jan

**Comment by Studentenfutter** [comment]
Wow das war schnell! Super, funktioniert mit deiner Anleitung einwandfrei! Danke!
