### ISSUE TITLE
Help Opening App

### ISSUE THREAD

**Issue by Paulemeister** [jansim/WG-SuchR#2]
Ich hab noch nie was mit R gemacht und bin auch nicht gut im debuggen. Ich bin der Anleitung gefolgt und hab die app gestartet. Als Output kriege ich
`Listening on http://127.0.0.1:6378

Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Warnung: Error in load.cities: Objekt 'Staedte.temp' nicht gefunden
  75: load.cities [R/data.R#53]
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Error in open.connection(con, "rb") : HTTP error 503.
Warnung: Error in load.cities: Objekt 'Staedte.temp' nicht gefunden
  75: load.cities [R/data.R#53]
`
Und es öffnet sich ein Browserfenster mit (URL:http://127.0.0.1:6378/)

### An error has occurred!

Objekt 'Staedte.temp' nicht gefunden

Irgendwelche ideen?

**Comment by jansim** [comment]
Hi Paulemeister,

was siehst du denn im Browserfenster? Kannst du das Interface der App sehen nur ohne daten, oder wird nicht einmal das interface der App geladen?

**Comment by Paulemeister** [comment]
Moin, danke für die Antwort, Es öffnet sich leider kein Interface, nur die fehlermeldung. Hier der code der angezeigten seite
```
<html>

<head>
  <title>An error has occurred</title>
</head>

<body>

<h1>An error has occurred!</h1>
<p>Objekt 'Staedte.temp' nicht gefunden</p>

</body>
</html>
```

**Comment by jansim** [comment]
Danke für die schnelle Antwort! Startest du die App in Rstudio oder normal in R? und gibt es eventuell noch eine Fehlermeldung bevor denen die du oben angegeben hast?

Das `Staedte.temp` nicht geladen werden kann ist nämlich glaube ich eher ein Folgefehler von etwas anderem 🤔

**Comment by Paulemeister** [comment]
Also Hier alle schritte die Ich gemacht habe:

1. Installieren von R x64 4.0.2
2. Installieren der Librarys
3. Laden der Librarys durch modifizierte RProfile.site
Angehängter Code:
```
.First <- function(){
 library(shiny)
 library(shinydashboard)
 library(rvest)
 library(jsonlite)
 library(tidyverse)
 library(ggplot2)
}
```
Output bei Startup:
```
Lade nötiges Paket: xml2

Attache Paket: ‘jsonlite’

The following object is masked from ‘package:shiny’:

    validate

-- Attaching packages --------------------------------------- tidyverse 1.3.0 --
v ggplot2 3.3.2     v purrr   0.3.4
v tibble  3.0.3     v dplyr   1.0.0
v tidyr   1.1.0     v stringr 1.4.0
v readr   1.3.1     v forcats 0.5.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x purrr::flatten()        masks jsonlite::flatten()
x readr::guess_encoding() masks rvest::guess_encoding()
x purrr::pluck()          masks rvest::pluck()
x jsonlite::validate()    masks shiny::validate()
```

Output bei händischem Laden:

```
> local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})
> local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})

Attache Paket: ‘shinydashboard’

The following object is masked from ‘package:graphics’:

    box

> local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})
Lade nötiges Paket: xml2
> local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})

Attache Paket: ‘jsonlite’

The following object is masked from ‘package:shiny’:

    validate

> local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})
-- Attaching packages --------------------------------------- tidyverse 1.3.0 --
v ggplot2 3.3.2     v purrr   0.3.4
v tibble  3.0.3     v dplyr   1.0.0
v tidyr   1.1.0     v stringr 1.4.0
v readr   1.3.1     v forcats 0.5.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter()         masks stats::filter()
x purrr::flatten()        masks jsonlite::flatten()
x readr::guess_encoding() masks rvest::guess_encoding()
x dplyr::lag()            masks stats::lag()
x purrr::pluck()          masks rvest::pluck()
x jsonlite::validate()    masks shiny::validate()
> local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})
> 
```
4. Setzen des Arbeitsverzeichnisse mit `setwd("C:/Users/Paulemeister/Downloads/WG-SuchR-master")`
5. Starten mit `runApp('inst/app')`

Das ist alles was Ich gemacht habe. Besten Dank nochmal

**Comment by jansim** [comment]
Hi @Paulemeister danke für die detaillierte Beschreibung, damit konnte ich den Fehler dann doch noch replizieren & finden! Ist durch den neuen fix in 9e4131e das Problem bei dir jetzt auch gelöst?

**Comment by Paulemeister** [comment]
Moin, jetzt bin ich schonmal einen schritt weiter gekommen. Es öffnet sich noch ein weiters Fenster mit der Überschrift "R Graphics: Device 2 (ACTIVE)" Die fehlermeldung im browser (nach wie vor kein bild) ist "An error has occurred!
plot.new has not been called yet" und im terminal steht "Warnung: Error in box: plot.new has not been called yet
  81: box". Zur info: Mein PC war eigentlich mal Kanadisch, Ich hab den gerade nochmal auf deustch umgestellt. Beim ersten mal starten hatte Ich im Browser sogar eine oberfläche mit kaputten umlauten (deswegen habe ich darauf meine systemsprache umgestellt), aber dannach konnte ich das nicht mehr reproduzieren (keine ahnung was ich da anders gemacht habe.)
Trotdem danke für den fix

**Comment by jansim** [comment]
Hmmm, da weiß ich jetzt leider auch nicht weiter.. evtl könntest du mal probieren das ganze über [Rstudio](https://rstudio.com/products/rstudio/download/) zu starten? Das ist manchmal etwas benutzerfreundlicher 🤔

**Comment by Paulemeister** [comment]
Da passiert genau das gleiche, schade

**Comment by shoeper** [comment]
Für mich hat die Zeile aus data.R mit dem Folgenden die Anzeige für einige Städe kaputt gemacht. Durch auskommentieren ging es erstmal.

```
if (nrow(data) > 0) data[is.nan(data$geschl.verh),]$geschl.verh <- NA # replace all NaN with NA
```

**Comment by jansim** [comment]
Sorry für die späte Antwort hier, aber das von dir beschriebene Problem @shoeper sollte jetzt behoben sein 👍
