### ISSUE TITLE
Suche nach freien Wohnung

### ISSUE THREAD

**Issue by thehappy1** [jansim/WG-SuchR#3]
Hi! 
Erstmal vielen lieben Dank für dieses klasse Projekt. Es gibt eine sehr gute Übersicht über die vorhandenen WGs. 
Jetzt bin ich aber auf der Suche nach freien Wohnungen. Gibt es eine Möglichkeit den Code so anzupassen, dass ich einfach nach freien Wohnungen crawle? 
Ich würde mich sehr über eine Antwort freuen. 
- Felix

**Comment by jansim** [comment]
Hi Felix,
Es ist leider noch nicht möglich den Wohntyp im UI anzupassen, aber wenn du eine kleine Änderung im source code vornimmst sollte das möglich sein. Und zwar kannst du den standard wohnungstyp in dieser [Zeile](https://github.com/jansim/WG-SuchR/blob/master/R/data.R#L156) ändern und es sollte dann automatisch beim nächsten launch der app verwendet werden. Ganz oben in der Datei stehen die möglichen wohntypen 😊

**Comment by thehappy1** [comment]
Hi Jansim, 
Danke für den Tipp. Ich probiere es mal aus! :-)
